apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  SQL_SERVER: sqlserverngv7580.database.windows.net
  SQL_USER: sqladminnGv7580
  SQL_PASSWORD: Password123!
  SQL_DBNAME: mydrivingDB